language: node_js
sudo: true
node_js:
  - '9.4.0'
cache:
  directories:
    - /*/**/node_modules
before_install:
  - git submodule update --init --remote --recursive
install:
  # - yarn bootstrap
  - travis_retry make ci-install
script:
  - yarn run build
  - yarn test
